### ISSUE TITLE
docker: Cannot GET /admin/pads

### ISSUE THREAD

**Issue by RefurioAnachro** [HarryBleckert/ep_adminpads3#15]
I'm running the docker release "etherpad/etherpad" behind an ninx-proxy / acme-companion combo. I have installed adminpads3 V3.0.22 via the admin page. I'm logged in there and when I enter the path /admin/pads in the URL I get the following error message:

Cannot GET /admin/pads

I feel stupid, is there some additional documentation I should have looked at?

**Comment by RefurioAnachro** [comment]
Here is an error message I found using `docker logs`:

[2024-02-21T22:02:41.417] [ERROR] settings - Failed to load hook function "/opt/etherpad-lite/plugin_packages/ep_adminpads3:eejsBlock_adminMenu" for plugin "ep_adminpads3" part "ep_adminpads3" hook set "hooks" hook "eejsBlock_adminMenu": Error: Cannot find module 'cheerio'
Require stack:
- /opt/etherpad-lite/plugin_packages/ep_adminpads3/index.js
- /opt/etherpad-lite/src/static/js/pluginfw/shared.js
- /opt/etherpad-lite/src/static/js/pluginfw/plugins.js
- /opt/etherpad-lite/src/node/server.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
    at Module._load (node:internal/modules/cjs/loader:985:27)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (/opt/etherpad-lite/plugin_packages/ep_adminpads3/index.js:12:11)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at loadFn (/opt/etherpad-lite/src/static/js/pluginfw/shared.js:27:12)
    at Object.extractHooks (/opt/etherpad-lite/src/static/js/pluginfw/shared.js:56:18)
    at exports.update (/opt/etherpad-lite/src/static/js/pluginfw/plugins.js:101:28)
    at async exports.start (/opt/etherpad-lite/src/node/server.js:144:5)

**Comment by RefurioAnachro** [comment]
Troubleshooting information says I'm running `Version number: 1.9.7`

**Comment by HarryBleckert** [comment]
According to the error message you posted above, "Cannot find module 'cheerio'", adminpads3 was not successfully installed and thus doesn't work.

**Comment by klardotsh** [comment]
For what it's worth, this is currently my UX when I go to the plugins manager of Etherpad and click "install" on this plugin. Even installing `cheerio` as an NPM dependency in my Docker container doesn't appear to solve the issue, which is somewhat surprising.

Put more simply, clicking install on this plugin in a stock Etherpad Lite admin panel currently does not produce a working installation of the plugin for me.

**Comment by HarryBleckert** [comment]
Hey Josh

Sorry, but I can't help resolving this problem, as I am not really an experienced nodejs developer, but simply forked adminpads2 because it lacked sortable columns and some other features I wanted to have.
However, I just tried again and I can uninstall and install adminpads3 using Etherpad 1.97 plugin manager.

Kind Regards
Harry

**Comment by RefurioAnachro** [comment]
How can I tell if it has installed properly? You seem to have a working copy, can we compare notes?

The files seem to be there:
```
$ ls -F /opt/etherpad-lite/plugin_packages/cheerio
LICENSE       Readme.md     lib/          package.json

$ ls -F /opt/etherpad-lite/plugin_packages/ep_adminpads3/
CONTRIBUTING.md  README.md        ep.json          locales/         static/
LICENSE          docs/            index.js         package.json     templates/
```

Other than in this directory adminpads3 is mentioned once:
```
$ find . -type f | grep -v ./plugin_packages/ep_adminpads3 | xargs grep ep_adminpads3 2>/dev/null
./var/installed_plugins.json:{"plugins":[{"name":"ep_prometheus_exporter","version":"0.0.6"},{"name":"ep_adminpads3","version":"3.0.22"},{"name":"ep_etherpad-lite","version":"1.9.7"}]}
```

**Comment by RefurioAnachro** [comment]
Errors all look like this
```
[2024-03-06T20:53:26.982] [ERROR] settings - Failed to load hook function "/opt/etherpad-lite/plugin_packages/ep_adminpads3:socketio" for plugin "ep_adminpads3" part "ep_adminpads3" hook set "hooks" hook "socketio": Error: Cannot find module 'cheerio'
```

Where the relevant bit is the second message, that it can't find the module cheerio. The difference between the lines is the function name, we get two messages like this for each `socketio`, `padRemove`, `padCreate`, and `eejsBlock_adminMenu`.

Searching for the last hook function seemed to find only files under plugin_packages/ep_adminpads3, but looking at the admin page's Troubleshooting Information, it seems at least the other hooks are used by other components, so that's okay... I guess.

Maybe it works with an older version of etherpad, here's a similar sounding problem from its upstream:

https://github.com/ether/etherpad-lite/issues/6182

**Comment by RefurioAnachro** [comment]
I just checked, it works fine with 1.9.6

**Comment by RefurioAnachro** [comment]
Maybe they'll fix it. Or someone keep an eye on that issue to see how the extension needs to be fixed. Or take a look at the changelog between 1.9.6 and 1.9.7 for more hints.

**Comment by JeremyRand** [comment]
1.9.7 added this PR that wasn't in 1.9.6: https://github.com/ether/etherpad-lite/pull/6018

Seems potentially relevant?

**Comment by SamTV12345** [comment]
It's fixed just to let you know :)
